### PR TITLE
Rename all functions containing a dash in order to improve compatibility

### PR DESCRIPTION
**Pull request by Wonno**

### CODE REVIEW

**Comment by fsaintjacques** [comment]
I don't think the file should be renamed.

**Comment by Wonno** [comment]
> I don't think the file should be renamed and the permission should be kept.

Totally agree. Updated.

**Comment by fsaintjacques** [comment]
Can you rebase with master, I added GHA unit testing, travis was somehow broken.

**Comment by fsaintjacques** [comment]
I verified locally and it passes the tests. Thank you!

**Comment by Wonno** [comment]
Successfully rebased.

**Pull request merged**
